apiVersion: apps/v1
kind: Deployment
metadata:
  name: showcase
  namespace: showcase
  labels: { app: showcase }
spec:
  replicas: 3
  selector:
    matchLabels: { app: showcase }
  strategy:
    type: RollingUpdate
    rollingUpdate: { maxUnavailable: 0, maxSurge: 1 }
  template:
    metadata:
      labels: { app: showcase }
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: web
          image: flask-showcase:lab1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef: { name: showcase-config }
          resources:
            requests: { cpu: 50m, memory: 96Mi }
            limits:   { cpu: 250m, memory: 256Mi }
          readinessProbe:
            httpGet: { path: /health, port: 5000 }
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /health, port: 5000 }
            initialDelaySeconds: 10
            periodSeconds: 10
